import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "./components/SideBar";
import TopNavbar from "./components/TopNavbar";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Task Management System</title>
      </head>
      <body className={inter.className}>
        <div className="w-full min-h-screen grid grid-cols-[280px,1fr]">
          <SideBar />
          <div className="">
            <TopNavbar />
            <ToastContainer />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
